# Generated by Django 5.1.3 on 2025-05-24 07:15

import User.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUsedID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_uid', models.PositiveIntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccounts',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uid', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
                ('Country', models.CharField(max_length=255, null=True)),
                ('State', models.CharField(max_length=255, null=True)),
                ('City', models.CharField(max_length=255, null=True)),
                ('Gender', models.CharField(max_length=255, null=True)),
                ('Date_of_Birth', models.DateField(null=True)),
                ('otp', models.CharField(max_length=6, null=True)),
                ('ProfilePic', models.ImageField(blank=True, null=True, upload_to=User.models.UserAccounts.FileName)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='customer', max_length=50)),
                ('amount_to_take', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount user owes to you', max_digits=12)),
                ('amount_to_give', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount you owe to the user', max_digits=12)),
                ('FMC_tokens', models.TextField(blank=True, default='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
