# Generated by Django 5.1.3 on 2025-05-31 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutwardBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('outward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='Sales.outward')),
            ],
        ),
        migrations.CreateModel(
            name='OutwardSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('COMPLETE', 'Complete'), ('INCOMPLETE', 'Incomplete')], default='NEW', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='outward',
            name='outward_slip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outwards', to='Sales.outwardslip'),
        ),
        migrations.CreateModel(
            name='OutwardSlipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.item')),
                ('outward_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Sales.outwardslip')),
            ],
        ),
    ]
