# Generated by Django 5.1.3 on 2025-05-31 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('available_quantity', models.IntegerField(default=0)),
                ('minimum_quantity', models.IntegerField(default=0)),
                ('suppliers', models.ManyToManyField(related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
